# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb1b20e2051860c092e1cb4d9b1e181aee13ad6682d17647345e859b35c86cd891bd7ad467450e5ea015d76b604a32a41717dd134bd1815c3af8bfb3b07d1d90

test:
  secret_key_base: df1e875da9e711efec2b6ab1a4eda0d3e4a210617d4bb41fcd6a19e7900501c8041baba4921fc30c7a3fb030f8d44a9fa4c27c3aceba1a3ce728c45a69b5187e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
